name: Java CI with Gradle

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 15
      uses: actions/setup-java@v2
      with:
        java-version: '15.0.1'
        distribution: 'adopt'
        cache: gradle
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: "355b6d02-a534-4fc1-a3b5-9f1888ad59e6"
        heroku_app_name: "library-backend-group-12"
        heroku_email: "aaronmills123@hotmail.com"


